#!/bin/sh

######## guess arch if not given
if [ -z $ARCH ]; then
        ARCH=$(machine -a)
fi

######## extract the release version from what's on ftp
REL=$(ftp -V -o - \
        https://ftp.openbsd.org/pub/OpenBSD/snapshots/${ARCH}/index.txt | \
        awk '/comp/ { print(substr($10, 5, 2)); }')

FILES="INSTALL.${ARCH} SHA256 SHA256.sig bsd bsd.rd base${REL}.tgz 
        comp${REL}.tgz game${REL}.tgz man${REL}.tgz xbase${REL}.tgz
        xfont${REL}.tgz xserv${REL}.tgz xshare${REL}.tgz" 

######## build download command
CMD="ftp -V"
for f in $FILES; do
        CMD="${CMD} $(cat /etc/installurl)/snapshots/${ARCH}/${f}"
done

# sgi follows a different rule, XXX
MPARCHS='alpha amd64 arm64 hppa luna88k macppc octeon sparc64'
for a in $MPARCHS; do
        if [ $a = $ARCH ]; then
                CMD="${CMD} $(cat /etc/installurl)/snapshots/${ARCH}/bsd.mp"
                break
        fi
done

######## run download command
$CMD
