#!/bin/sh

get_release() {
    rel=$(ftp -V -o - \
        https://ftp.openbsd.org/pub/OpenBSD/snapshots/${arch}/index.txt | \
        awk '/comp/ { print(substr($10, 5, 2)); }')
    return $rel
}

start_download() {
    files="INSTALL.${arch} SHA256 SHA256.sig bsd bsd.rd base${rel}.tgz
    comp${rel}.tgz game${rel}.tgz man${rel}.tgz xbase${rel}.tgz
    xfont${rel}.tgz xserv${rel}.tgz xshare${rel}.tgz" 

    # download and parse mirrors list
    servers=$(ftp -V -o - https://www.openbsd.org/build/mirrors.dat | sed -n '/^UHS[[:space:]]*/s///p')

    echo 'Servers available:'
    PS3='Choose a server: '
    select server in ${servers}; do
        if [ ${server} ]; then
            for f in ${files}; do
                fileurl="${server}${prefix}${f}"
                allfiles="${allfiles} ${fileurl}"
            done
            ftp -V $allfiles

            # arch specific
            if [ ${arch} = "amd64" ]; then
                ftp -V ${server}${prefix}bsd.mp
            fi

            break
        else
            echo 'invalid selection'
        fi
    done
}

# some archs have specific kernels/files (sgi), some have mp support and
# some don't; so we have to define which arch to download to not try to
# download files that don't exist
archs='amd64 armv7'

echo 'Archs available: '
PS3='Choose arch: '
select arch in ${archs}; do
    break
done
prefix="snapshots/${arch}/"

get_release
rel=$?

start_download
