#!/bin/sh

DEVICE=$1
BACKUPDIR="home"

if [ -z $DEVICE ]; then
    echo "usage: $0 device"
else
    cd
    rsync -rlptv --delete --exclude-from=$HOME/.rsync-exclude-file \
	. mnt/$DEVICE/$BACKUPDIR-`hostname -s`
fi
