#!/bin/sh

DEVICE=$1
BACKUPDIR="home-`hostname -s`"

if [ -z $DEVICE ]; then
    echo "usage: $0 device"
else
    cd
    rsync -rlptv --delete --exclude-from=$HOME/.rsync-exclude-file \
	. /mnt/$DEVICE/$BACKUPDIR
fi

echo `date` > /mnt/$DEVICE/LASTBACKUP-`hostname -s`
