#!/bin/sh
#
# script to convert mp3 files to wav
#
# Copyright (c) 2009, Daniel Bolgheroni.
#
# REQUIREMENTS:
# remember you need audio/mpg321

for i in *.mp3
do
	echo "===> converting \"$i\""
	mpg321 -q -w "$i.wav" "$i"
done

  
