#!/bin/sh

TOOL=iconv

if [ -z $1 ]; then
    echo "usage: $0 [file ...]"
else
    for filename in "$@"; do
	if [ -e $filename ]; then
	    mv $filename $filename.tmp
	    $TOOL -s -f ISO-8859-1 -t UTF-8 $filename.tmp > $filename
	    rm -fr $filename.tmp
	else
	    echo "$0: file not found"
	fi
    done
fi
