#!/bin/ksh
#
# no error checks

IF=$1

if [ -z $IF ]; then
    echo "usage: $0 [interface]"
else
    nwids=`sudo ifconfig $IF scan | grep 'nwid' | \
	sed 's/^[[:space:]]//; s/.*nwid //; s/ chan.*//; s/^\".*"//' | \
	sort | uniq`

    PS3='nwid? '
    select nwid in $nwids; do
	if [ $nwid ]; then
	    read wpakey?'wpakey? '
	    sudo ifconfig $IF nwid $nwid wpakey $wpakey
	    sudo dhclient $IF
	    break
	else
	    echo 'invalid nwid'
	fi
    done
fi